weights: ''''''
cfg: ./models/yolov5m.yaml
data: ./data.yaml
hyp: data/hyp.scratch.yaml
epochs: 100
batch_size: 4
img_size:
- 416
- 416
rect: false
resume: false
nosave: true
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: true
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
log_imgs: 16
workers: 8
project: runs/train
name: yolov5m_results
exist_ok: false
total_batch_size: 4
world_size: 1
global_rank: -1
save_dir: runs\train\yolov5m_results3
